---
include:
  - board: nice_nano_v2
    shield: keyball39_left
  - board: nice_nano_v2
    shield: keyball39_right
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: settings_reset
